Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    config.vm.synced_folder "./mirror", "/home/vagrant/host-mirror"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        # vb.gui = true
    end
end
